dashboard/urls.py
"""Defines URL patterns for the GuruShop dashboard"""

from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    #Dashboard Home
    path('', views.dashboard, name='dash_index'),

    #Users Profile
    path('profile/', views.profile, name='profile'),

    #Products Page
    path('products/', views.products, name='products'),

    #Categories Page
    path('categories/', views.categories, name='categories'),

    #Test Page
    path('test/', views.test, name='test'),

    #Add Product Page
    path('add-product/', views.addProduct, name='add-product'),

]

gurushop/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from rest_framework import routers
from store import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

router = routers.DefaultRouter()
router.register(r'products', views.ProductsViewSet, 'products')
# popular products 
router.register(r'categories', views.CategoriesViewSet, 'categories')
router.register(r'types', views.TypesViewSet)
router.register(r'tags', views.TagViewSet) 
router.register(r'shops', views.ShopViewSet)
router.register(r'authors', views.AuthorViewSet)
# top authors 
router.register(r'manufacturers', views.ManufacturerViewSet)
# top manufacturers 
router.register(r'coupons', views.CouponViewSet)
# coupons verify
router.register(r'orders', views.OrderViewSet)
router.register(r'order-status', views.OrderStatusViewSet)
# refunds 
router.register(r'orders/checkout/verify', views.VerifiedCheckoutDataViewSet)
# downloads 
# downloads digital file
router.register(r'users', views.UserViewSet)
router.register(r'adress', views.UserAddressViewSet)
# user me -- Done below
# token -- Done below 
# user register -- Done below 
# forgot password 
# verify forget password 
# change password 
# user logout -- Done below 
# subscribe to newsletter 
# contact us 
# social login token 
# verify otp code 
# otp login 
# update contact 
router.register(r'settings', views.SettingsViewSet, 'settings')
router.register(r'attachments', views.AttachmentViewSet)
router.register(r'order-pivot', views.OrderPivot)




urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls,)),
    path('api/user/', include('store.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_refresh'),
    path('users/', include('users.urls')),
    path('', include('dashboard.urls')),
    path('store/', include('store.urls')),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    #path('account/', include('django.contrib.auth.urls')),
    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

# app_name = 'store'

urlpatterns = [
    path('register/', views.UserCreate.as_view(), name='create_user'),
    path('me/', views.LoadUserView.as_view(), name='load_user'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

dashboard/models.py
from django.db import models

# Create your models here.



dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from store.models import *

# Create your views here.


#@login_required
def dashboard(request):
    """The dashboard for user admins on Gurushop"""
    return render(request, 'dashboard/index.html')

#@login_required
def profile(request):
    """A profile for the logged-in user to manage"""
    return render(request, 'dashboard/profile.html')

def products(request):
    """The products table in admin"""
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'dashboard/products.html', context)

def categories(request):
    """The categories table in admin"""
    categories = Categories.objects.all()
    context = {'categories': categories}
    return render(request, 'dashboard/categories.html', context)


def test(request):
    """A profile for the logged-in user to manage"""
    return render(request, 'dashboard/test.html')

def addProduct(request):
    """A profile for the logged-in user to manage"""
    return render(request, 'dashboard/add-product.html')

dashboard/templates/dashboard/add-product.html
{% extends "dashboard/base.html" %}

dashboard/templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="description" content="">
  <meta name="author" content="Dashboard">
  <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
  <title>Dataguru Dashboard For Gurushop</title>

  
  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <link href="{% static 'lib/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
{% block css %}
  
{% endblock css %}
  <!-- animation css -->
  <link rel="stylesheet" href="{% static 'plugins/animation/css/animate.min.css' %}">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/new_style.css' %}" rel="stylesheet">
  <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
  <script src="{% static 'lib/chart-master/Chart.js' %}"></script>

</head>

<body>
  <section id="container">
    <!-- **********************************************************************************************************************************************************
        TOP BAR CONTENT & NOTIFICATIONS
        *********************************************************************************************************************************************************** -->
    <!--header start-->

    <!--header end-->
    <!-- **********************************************************************************************************************************************************
        MAIN SIDEBAR MENU
        *********************************************************************************************************************************************************** -->
    <!--sidebar start-->
    <!-- [ Pre-loader ] start -->
    <div class="loader-bg">
      <div class="loader-track">
          <div class="loader-fill"></div>
      </div>
  </div>

  

    <!-- sidebar -->
      
      {% include 'dashboard/sidebar.html' %}

    <!--sidebar end-->



    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->

        
        {% block content %}
        

        {% endblock content %}
        

   <!-- *************************************************************************************************************************************************************
        MAIN CONTENT
        *************************************************************************************************************************************************************-->


    <!--footer start-->
    <footer class="site-footer">
      <div class="text-center">
        <p>
          &copy; Copyrights <strong>Gurushop</strong>. All Rights Reserved
        </p>
        <div class="credits">
        
          Created by <a href="https://templatemag.com/">Dataguru</a>
        </div>
        <a href="{% url 'dashboard:dash_index' %}" class="go-top">
          <i class="fa fa-angle-up"></i>
          </a>
      </div>
    </footer>
    <!--footer end-->
  </section>

  <!-- js placed at the end of the document so the pages load faster -->
  <script src="{% static 'lib/jquery/jquery.js' %}"></script>
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script type="text/javascript" language="javascript" src="{% static 'lib/advanced-datatable/js/jquery.js' %}"></script>
  <script src="{% static 'js/vendor-all.min.js' %}"></script>
  <script src="{% static 'js/pcoded.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
  <script class="include" type="text/javascript" src="{% static 'lib/jquery.dcjqaccordion.2.7.js' %}"></script>
  <script src="{% static 'lib/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'lib/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <script src="{% static 'lib/jquery.sparkline.js' %}"></script>
  <!--common script for all pages-->
  <script src="{% static 'lib/common-scripts.js' %}"></script>

  <script type="text/javascript" src="{% static 'lib/gritter/js/jquery.gritter.js' %}"></script>
  <script type="text/javascript" src="{% static 'lib/gritter-conf.js' %}"></script>
  <!--script for this page-->
  <script src="{% static 'lib/sparkline-chart.js' %}"></script>
  <script src="{% static 'lib/zabuto_calendar.js' %}"></script>
{% block scripts %}


{% endblock scripts %}

  
</body>

</html>

dashboard/templates/dashboard/categories.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block css %}
<link href="{% static 'lib/advanced-datatable/css/demo_page.css" rel="stylesheet' %}" />
  <link href="{% static 'lib/advanced-datatable/css/demo_table.css" rel="stylesheet' %}" />
  <link rel="{% static 'stylesheet" href="lib/advanced-datatable/css/DT_bootstrap.css' %}" />
{% endblock css %}


{% block content %}
<section class="pcoded-main-container">
    <section class="wrapper">
      <h3>Categories</h3>
      <div class="row mb">
        <!-- page start-->
        <div class="content-panel">
          <div class="adv-table">
            <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
              <thead>
                <tr>
                  <th>Category Name</th>
                  <th>Slug</th>
                  <th>Created</th>
                  <th>Type</th>
                </tr>
              </thead>
              <tbody>
                {% for category in categories %}
                <tr>
                  <td>{{category.name}}</td>
                  <td>{{category.slug}}</td>
                  <td>{{category.created_at}}</td>
                  <td>{{category.type}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <!-- page end-->
      </div>
      <!-- /row -->
    </section>
    <!-- /wrapper -->
  </section>
{% endblock content %}


{% block scripts %}
<script type="text/javascript" language="javascript" src="{% static 'lib/advanced-datatable/js/jquery.dataTables.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/advanced-datatable/js/DT_bootstrap.js' %}"></script>

<script type="text/javascript">
    /* Formating function for row details */
    function fnFormatDetails(oTable, nTr) {
      var aData = oTable.fnGetData(nTr);
      var sOut = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
      sOut += '<tr><td>Rendering engine:</td><td>' + aData[1] + ' ' + aData[4] + '</td></tr>';
      sOut += '<tr><td>Link to source:</td><td>Could provide a link here</td></tr>';
      sOut += '<tr><td>Extra info:</td><td>And any further details here (images etc)</td></tr>';
      sOut += '</table>';

      return sOut;
    }

    $(document).ready(function() {
      /*
       * Insert a 'details' column to the table
       */
      var nCloneTh = document.createElement('th');
      var nCloneTd = document.createElement('td');
      nCloneTd.innerHTML = '<img src="lib/advanced-datatable/images/details_open.png">';
      nCloneTd.className = "center";

      $('#hidden-table-info thead tr').each(function() {
        this.insertBefore(nCloneTh, this.childNodes[0]);
      });

      $('#hidden-table-info tbody tr').each(function() {
        this.insertBefore(nCloneTd.cloneNode(true), this.childNodes[0]);
      });

      /*
       * Initialse DataTables, with no sorting on the 'details' column
       */
      var oTable = $('#hidden-table-info').dataTable({
        "aoColumnDefs": [{
          "bSortable": false,
          "aTargets": [0]
        }],
        "aaSorting": [
          [1, 'asc']
        ]
      });

      /* Add event listener for opening and closing details
       * Note that the indicator for showing which row is open is not controlled by DataTables,
       * rather it is done here
       */
      $('#hidden-table-info tbody td img').live('click', function() {
        var nTr = $(this).parents('tr')[0];
        if (oTable.fnIsOpen(nTr)) {
          /* This row is already open - close it */
          this.src = "lib/advanced-datatable/media/images/details_open.png";
          oTable.fnClose(nTr);
        } else {
          /* Open this row */
          this.src = "lib/advanced-datatable/images/details_close.png";
          oTable.fnOpen(nTr, fnFormatDetails(oTable, nTr), 'details');
        }
      });
    });
  </script>



{% endblock scripts %}

dashboard/templates/dashboard/products.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block css %}
<link href="{% static 'lib/advanced-datatable/css/demo_page.css" rel="stylesheet' %}" />
  <link href="{% static 'lib/advanced-datatable/css/demo_table.css" rel="stylesheet' %}" />
  <link rel="{% static 'stylesheet" href="lib/advanced-datatable/css/DT_bootstrap.css' %}" />
{% endblock css %}


{% block content %}
<section class="pcoded-main-container">
    <section class="wrapper">
      <h3>Products List</h3>
      <div class="row mb">
        <!-- page start-->
        <div class="content-panel">
          <div class="adv-table">
            <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
              <thead>
                <tr>
                  <th>Product Name</th>
                  <th>Description</th>
                  <th class="hidden-phone">Price</th>
                  <th class="hidden-phone">Quantity</th>
                  <th class="hidden-phone">Slug</th>
                </tr>
              </thead>
              <tbody>
                {% for product in products %}
                <tr>
                  <td>{{product.name}}</td>
                  <td>{{product.description}}</td>
                  <td>${{product.price}}</td>
                  <td>{{product.quantity}}</td>
                  <td>{{product.slug}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <!-- page end-->
      </div>
      <!-- /row -->
    </section>
    <!-- /wrapper -->
  </section>
{% endblock content %}


{% block scripts %}
<script type="text/javascript" language="javascript" src="{% static 'lib/advanced-datatable/js/jquery.dataTables.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/advanced-datatable/js/DT_bootstrap.js' %}"></script>

<script type="text/javascript">
    /* Formating function for row details */
    function fnFormatDetails(oTable, nTr) {
      var aData = oTable.fnGetData(nTr);
      var sOut = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
      sOut += '<tr><td>Rendering engine:</td><td>' + aData[1] + ' ' + aData[4] + '</td></tr>';
      sOut += '<tr><td>Link to source:</td><td>Could provide a link here</td></tr>';
      sOut += '<tr><td>Extra info:</td><td>And any further details here (images etc)</td></tr>';
      sOut += '</table>';

      return sOut;
    }

    $(document).ready(function() {
      /*
       * Insert a 'details' column to the table
       */
      var nCloneTh = document.createElement('th');
      var nCloneTd = document.createElement('td');
      nCloneTd.innerHTML = '<img src="lib/advanced-datatable/images/details_open.png">';
      nCloneTd.className = "center";

      $('#hidden-table-info thead tr').each(function() {
        this.insertBefore(nCloneTh, this.childNodes[0]);
      });

      $('#hidden-table-info tbody tr').each(function() {
        this.insertBefore(nCloneTd.cloneNode(true), this.childNodes[0]);
      });

      /*
       * Initialse DataTables, with no sorting on the 'details' column
       */
      var oTable = $('#hidden-table-info').dataTable({
        "aoColumnDefs": [{
          "bSortable": false,
          "aTargets": [0]
        }],
        "aaSorting": [
          [1, 'asc']
        ]
      });

      /* Add event listener for opening and closing details
       * Note that the indicator for showing which row is open is not controlled by DataTables,
       * rather it is done here
       */
      $('#hidden-table-info tbody td img').live('click', function() {
        var nTr = $(this).parents('tr')[0];
        if (oTable.fnIsOpen(nTr)) {
          /* This row is already open - close it */
          this.src = "lib/advanced-datatable/media/images/details_open.png";
          oTable.fnClose(nTr);
        } else {
          /* Open this row */
          this.src = "lib/advanced-datatable/images/details_close.png";
          oTable.fnOpen(nTr, fnFormatDetails(oTable, nTr), 'details');
        }
      });
    });
  </script>



{% endblock scripts %}

dashboard/templates/dashboard/profile.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block content %}
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper site-min-height">
          <h3><i class="fa fa-angle-right"></i> Hello Username.</h3>
          <div class="row mt">
            <div class="col-lg-12">
              <p>This is just a page to show that you have successfully set up an account.</p>
            </div>
          </div>
        </section>
        <!-- /wrapper -->
      </section>
      <!-- /MAIN CONTENT -->
      <!--main content end-->
{% endblock content %}

dashboard/templates/dashboard/sidebar.html
<nav class="pcoded-navbar">
    <div class="navbar-wrapper">
        <div class="navbar-brand header-logo">
            <a target="_blank" 
               href="#" class="b-brand">
                <div class="b-bg">
                    <i class="feather icon-trending-up"></i>
                </div>
                <span class="b-title">DataGuru Shop</span>
            </a>
            <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
        </div>
        <div class="navbar-content scroll-div">
            <ul class="nav pcoded-inner-navbar">
                <li class="nav-item pcoded-menu-caption">
                    <label>Welcome</label>
                </li>
                <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
                    class="nav-item {% if 'index' in segment %} active {% endif %}">
                    <a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">Dashboard</span></a>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Shop</label>
                </li>
                <li data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds" class="nav-item pcoded-hasmenu">
                    <a href="javascript:" ><span class="pcoded-micon"><i class="feather icon-box"></i></span><span class="pcoded-mtext">Products</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="{% url 'dashboard:products' %}" class="">All Products</a></li>
                        <li class=""><a href="{% url 'dashboard:categories' %}" class="">Categories</a></li>
                        <li class=""><a href="{% url 'dashboard:add-product' %}" class="">Add Products</a></li>
                    </ul>
                </li>
                <li data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds" class="nav-item pcoded-hasmenu">
                    <a href="javascript:" ><span class="pcoded-micon"><i class="feather icon-grid"></i></span><span class="pcoded-mtext">Orders</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="{% url 'dashboard:products' %}" class="">Order List</a></li>
                        <li class=""><a href="{% url 'dashboard:categories' %}" class="">Categories</a></li>
                        <li class=""><a href="{% url 'dashboard:add-product' %}" class="">Add Products</a></li>
                    </ul>
                </li>
                <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
                    class="nav-item {% if 'index' in segment %} active {% endif %}">
                    <a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext">Customers</span></a>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Forms & table</label>
                </li>
                <li data-username="form elements advance componant validation masking wizard picker select" 
                    class="nav-item {% if 'ui-forms' in segment %} active {% endif %}">
                    <a href="/ui-forms.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-file-text"></i></span><span class="pcoded-mtext">Form elements</span></a>
                </li>
                <li data-username="Table bootstrap datatable footable" 
                    class="nav-item {% if 'ui-tables' in segment %} active {% endif %}">
                    <a href="/ui-tables.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-server"></i></span><span class="pcoded-mtext">Table</span></a>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Chart & Maps</label>
                </li>
                <li data-username="Charts Morris" 
                    class="nav-item {% if 'charts-morris' in segment %} active {% endif %}">
                    <a href="/charts-morris.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-pie-chart"></i></span><span class="pcoded-mtext">Chart</span></a></li>
                <li data-username="Maps Google" 
                     class="nav-item {% if 'maps-google' in segment %} active {% endif %}">
                    <a href="/maps-google.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-map"></i></span><span class="pcoded-mtext">Maps</span></a></li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Pages</label>
                </li>
                <li data-username="Authentication Sign up Sign in reset password Change password Personal information profile settings map form subscribe" class="nav-item pcoded-hasmenu">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-lock"></i></span><span class="pcoded-mtext">Authentication</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="/auth-reset-pass.html" class="">Reset Pass</a></li>
                        <li class=""><a href="/login.html" class="">Login (template)</a></li>
                        <li class=""><a href="/register.html" class="">Register (template)</a></li>
                    </ul>
                </li>
                <li data-username="Sample Page" 
                    class="nav-item {% if 'page-blank' in segment %} active {% endif %}">
                    <a href="/page-blank.html" class="nav-link"><span class="pcoded-micon"><i class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Sample page</span></a></li>
                <li data-username="Sample Page" class="nav-item"><a href="/page-404.html" class="nav-link"><span class="pcoded-micon"><i class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Error 404</span></a></li>

                <li data-username="Disabled Menu" class="nav-item">
                    <a href="#" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-power"></i></span><span class="pcoded-mtext">Logout</span>
                    </a>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>More Resources</label>
                </li>                    
                <li data-username="Support Page" class="nav-item ">
                    <a target="_blank" href="#" class="nav-link">
                        <span class="pcoded-micon">
                            <i class="feather icon-headphones"></i>
                        </span>
                        <span class="pcoded-mtext">Support</span>
                    </a>
                </li>
                <li data-username="Support Page" class="nav-item ">
                    <a target="_blank" href="#" class="nav-link">
                        <span class="pcoded-micon">
                            <i class="feather icon-tag"></i>
                        </span>
                        <span class="pcoded-mtext">PRO Version</span>
                    </a>
                </li>                     
            </ul>
        </div>
    </div>
</nav>